import libs = sol2%lib{sol2}

for t: source/cxx{*}
{
  n = $name($t)
  ./: exe{$n}: $t $libs testscript
}

cxx.poptions += -DSOL_PRINT_ERRORS=1 -DSOL_ALL_SAFETIES_ON=1

if ($cxx.target.system != 'win32-msvc')
  cxx.libs += -pthread
