for x: cxx{**}
{
  # Prevent build targets from being backlinked
  # into the symlinked 'source/' directory.
  # We construct a parallel target directory tree to keep all targets
  # separate from the upstream source code during package development.
  #
  d = $relative($directory($x), [dir_path] source/)
  n = $name($x)
  ./: $d/exe{$n}: $x $sol2 testscript
}
