# Dependencies
#
import libs = lua%lib{lua}

# Headers and Sources
#
lib{sol2}: sol/{hxx h}{**} $libs

# Build options.
#
cxx.poptions =+ "-I$src_base"

# Export options.
#
lib{sol2}:
{
  cxx.export.poptions = "-I$src_base"
  cxx.export.libs = $libs
}

# Installation
#
{hxx h}{*}:
{
  install         = include/
  install.subdirs = true
}
